# Generated by Django 4.1.7 on 2023-02-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Verb",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("infinitif", models.CharField(max_length=30)),
                ("translation", models.CharField(max_length=30)),
            ],
        ),
    ]
